# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 22:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_date_added',
            field=models.DateField(default=datetime.datetime(2017, 11, 9, 22, 17, 38, 775335)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Objeto', 'Objeto'), ('Auto', 'Auto')], default='Objeto', max_length=255),
        ),
    ]
