# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20171109_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_date_added',
            new_name='issue_date',
        ),
        migrations.AddField(
            model_name='issue',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
