# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20171111_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='aprobado_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='desaprado_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='revisado_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Visado', 'Visado'), ('Revisado', 'Revisado'), ('Aprobado', 'Aprobado'), ('Desaprobado', 'Desaprobado')], default='Nuevo', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='visado_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
