# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20171111_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='desaprado_date',
            new_name='desaprobado_date',
        ),
    ]
