# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_auto_20171111_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='aprobado_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='desaprobado_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='revisado_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='visado_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
