# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_auto_20171111_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tomado_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Tomado', 'Tomado'), ('Visado', 'Visado'), ('Revisado', 'Revisado'), ('Aprobado', 'Aprobado'), ('Desaprobado', 'Desaprobado')], default='Nuevo', max_length=255),
        ),
    ]
