# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_auto_20171111_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Tomado', 'Tomado'), ('Visado', 'Visado'), ('Presupuestado', 'Presupuestado'), ('Aprobado', 'Aprobado'), ('Desaprobado', 'Desaprobado')], default='Nuevo', max_length=255),
        ),
    ]
