# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 22:22
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_auto_20171115_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
