# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0009_issue_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='case_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
